In [1]:
"""
This notebook contains the code for bit plane slicing of the images and their reproduction using subset of the planes
"""

'\nThis notebook contains the code for bit plane slicing of the images and their reproduction using subset of the planes\n'

In [2]:
import cv2 as cv;
import numpy as np;

In [3]:
# reading the image

Wasam = cv.imread("./Wasam.enc",cv.IMREAD_GRAYSCALE)
AbdulRehman = cv.imread("./AbdulRehman.jpg",cv.IMREAD_GRAYSCALE)



In [4]:
def show(prompt,img):
    cv.namedWindow(prompt, cv.WINDOW_NORMAL)
    cv.imshow(prompt, img)
    cv.waitKey(0) 
    cv.destroyAllWindows()


In [5]:
show("Wasam ",Wasam)
show("AbdulRehman ",AbdulRehman)


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/hasib/.local/lib/python3.10/site-packages/cv2/qt/plugins"


In [6]:
""" regenrating the image using only one plane at time, 
    images will be shown as black and white because one plane means 
    we have only information in powers of 2 i.e, 1,2,4,8,...
    so to make the information more visible we scale up the information
    to 255 making it look like an black and white image
"""

def simulateBitPlanes(Img):
    for i in range(8):
        bitplane = Img & (1<<i);
        bitplane = np.where(bitplane==2**i,255,0).astype(np.uint8)
        show(f"regenrated from bitplane level {i} ",bitplane)


In [7]:
simulateBitPlanes(Wasam)
simulateBitPlanes(AbdulRehman)

In [19]:
def mergeImages(img1,img2):
    """
    This function takes in two images and store second image into the first image,
    and return the firstImage(having second image embedded in it)
    """

    arr1 = np.array(img1)
    arr2 = np.array(img2)

    arr1 = arr1 & (0b11110000);

    arr1 = arr1.astype(np.uint8);

    arr2 = arr2 & (0b11110000)

    arr2 = arr2.astype(np.uint8);

    show(f"regenrated from 4 MS bitplane levels of first image ",arr1)
    show(f"regenrated from 4 MS bitplane levels of second image ",arr2)
    arr2 = (arr2 >> 4);
    # show(f"regenrated from 3 MS bitplane levels of second image ",img2)

    arr1 = arr1 | arr2;

    show(f"merged Images ",arr1)
    return arr1




In [20]:
# reading the image

Wasam = cv.imread("./Wasam.enc",cv.IMREAD_GRAYSCALE)
AbdulRehman = cv.imread("./AbdulRehman.jpg",cv.IMREAD_GRAYSCALE)


mergedImage = mergeImages(Wasam,AbdulRehman)

In [21]:
## extracting the merged image from the last 4 bits
mergedImage = mergedImage & (0b00001111)
print("information in lower 4 bits ",mergedImage)
mergedImage = mergedImage << 4;
print("information moved to upper 4 bits ",mergedImage)

show("regenerated second image ",mergedImage)

information in lower 4 bits  [[6 4 4 ... 6 6 6]
 [6 6 5 ... 6 6 7]
 [6 6 6 ... 7 7 8]
 ...
 [8 8 8 ... 4 4 4]
 [7 7 7 ... 4 4 4]
 [6 6 6 ... 4 4 4]]
information moved to upper 4 bits  [[ 96  64  64 ...  96  96  96]
 [ 96  96  80 ...  96  96 112]
 [ 96  96  96 ... 112 112 128]
 ...
 [128 128 128 ...  64  64  64]
 [112 112 112 ...  64  64  64]
 [ 96  96  96 ...  64  64  64]]
